#!/bin/sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

macos_version=$(sw_vers -productVersion | cut -d '.' -f 1)
if [ "$macos_version" -ne 26 ]; then
    echo "This utility requires macOS 26."
    exit 1
fi

if csrutil status | grep -q "disabled"; then
    printf "✅ System Integrity Protection (SIP) is disabled.\n"
else
    printf 'For this to work, you need to turn off System Integrity Protection by running `csrutil disable` in recoveryOS.\n'
    printf 'https://developer.apple.com/documentation/security/disabling-and-enabling-system-integrity-protection\n'
    exit 1
fi

# You can download and extract Dock.app and Launchpad.app from the IPSWs youself.
# You can compare the shasum of your own extraction with what's in the repo, which matches.
# You can also use your own .app bundles by placing them in ./assets.
# https://theapplewiki.com/wiki/Beta_Firmware/Mac/26.x
# https://theapplewiki.com/wiki/Keys:CheerSeed_25A5316i_(Mac15,12)
# https://theapplewiki.com/wiki/Keys:CheerSeed_25A5306g_(iMac21,2)
# https://updates.cdn-apple.com/2025SummerSeed/fullrestores/082-89871/D95E6C0D-147C-4F0D-878B-A4534D9B4763/UniversalMac_26.0_25A5316i_Restore.ipsw
# https://updates.cdn-apple.com/2025SummerSeed/fullrestores/082-72248/F32F08F8-FC66-4D24-847B-F03C6CF7C410/UniversalMac_26.0_25A5306g_Restore.ipsw
# aea decrypt -i ~/Downloads/UniversalMac_26.0_25A5316i_Restore/044-44752-107.dmg.aea -o ~/Downloads/UniversalMac_26.0_25A5316i_Restore/044-44752-107.dmg -key-value 'base64:6AgFrh6bxZ4tKfIKnDwvT1aXLbgRivDiLDmw/AF9vfU='
# aea decrypt -i ~/Downloads/UniversalMac_26.0_25A5306g_Restore/044-44752-094.dmg.aea -o ~/Downloads/UniversalMac_26.0_25A5306g_Restore/044-44752-094.dmg -key-value 'base64:SwvusTPGzVJX9bJa6t5EWTpmLHFnAfC8Zft3VUpPKGY=' 

if [ -f ~/Library/LaunchAgents/com.launchpad.agent.plist ]; then
    printf "It appears that you have installed Launchpad.\n"
    read -r -p "Do you want to uninstall these modifications and restore to system defaults? [Y/n] " response </dev/tty
    case "$response" in
        [nN][oO]|[nN]) 
            ;;
        *)
            launchctl unload ~/Library/LaunchAgents/com.launchpad.agent.plist
            launchctl unload /Users/Shared/.launchpad/com.apple.Dock.plist
            launchctl load /System/Library/LaunchAgents/com.apple.Dock.plist
            launchctl start com.apple.Dock.agent
            rm ~/Library/LaunchAgents/com.launchpad.agent.plist
            rm -rf /Users/Shared/.launchpad
            rm -rf /Applications/Launchpad.app
            exit 1
            ;;
    esac
else
    printf "Reinstalling Launchpad...\n"
fi

printf 'Printing signing information for Dock.app pre-extracted from UniversalMac_26.0_25A5316i_Restore.ipsw...\n'
codesign -dvvv ./assets/Dock.app

printf 'Copying Dock.app pre-extracted from UniversalMac_26.0_25A5316i_Restore.ipsw...\n'
xattr -cr ./assets/Dock.app
mkdir -p /Users/Shared/.launchpad/
cp -R ./assets/Dock.app /Users/Shared/.launchpad

printf 'Printing signing information for Launchpad.app pre-extracted from UniversalMac_26.0_25A5306g_Restore.ipsw...\n'
codesign -dvvv ./assets/Launchpad.app

printf 'Copying Launchpad.app pre-extracted from UniversalMac_26.0_25A5306g_Restore.ipsw...\n'
xattr -cr ./assets/Launchpad.app
cp -R ./assets/Launchpad.app /Applications

printf 'Updating Info.plist to unhide Launchpad.app...\n'
plutil -remove LSRequiredFeatureFlags /Applications/Launchpad.app/Contents/Info.plist

printf 'Breaking Launchpad.app out of icon jail...\n'
xattr -wx com.apple.FinderInfo '00 00 00 00 00 00 00 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00' /Applications/Launchpad.app
ditto -xk ./assets/icon.zip /Applications/Launchpad.app

printf 'Reloading Dock to apply changes...\n'
xattr -cr ./assets/Launchpad
cp ./assets/Launchpad /Users/Shared/.launchpad
chmod +x /Users/Shared/.launchpad/Launchpad

xattr -cr ./assets/com.launchpad.agent.plist
cp ./assets/com.launchpad.agent.plist ~/Library/LaunchAgents
launchctl unload ~/Library/LaunchAgents/com.launchpad.agent.plist > /dev/null 2>&1
launchctl load ~/Library/LaunchAgents/com.launchpad.agent.plist
