#!/bin/sh

macos_version=$(sw_vers -productVersion | cut -d '.' -f 1)
if [ "$macos_version" -ne 26 ]; then
    echo "This utility requires macOS 26."
    exit 1
fi

if csrutil status | grep -q "disabled"; then
    printf "✅ System Integrity Protection (SIP) is disabled.\n"
else
    printf 'For this to work, you need to turn off System Integrity Protection by running `csrutil disable` in recoveryOS.\n'
    printf 'https://developer.apple.com/documentation/security/disabling-and-enabling-system-integrity-protection\n'
    exit 1
fi

cp /System/Library/LaunchAgents/com.apple.Dock.plist /Users/Shared/.launchpad
if defaults read /Library/Preferences/FeatureFlags/Domain/SwiftUI.plist Solarium | grep -q "Enabled = 0"; then
    plutil -insert EnvironmentVariables -xml "<dict><key>FEATUREFLAGS_DISABLED</key><string>SpotlightUI/SpotlightPlus:SwiftUI/Solarium</string></dict>" /Users/Shared/.launchpad/com.apple.Dock.plist
else
    plutil -insert EnvironmentVariables -xml "<dict><key>FEATUREFLAGS_DISABLED</key><string>SpotlightUI/SpotlightPlus</string></dict>" /Users/Shared/.launchpad/com.apple.Dock.plist
fi
plutil -replace Program -string /Users/Shared/.launchpad/Dock.app/Contents/MacOS/Dock /Users/Shared/.launchpad/com.apple.Dock.plist

launchctl unload /Users/Shared/.launchpad/com.apple.Dock.plist
launchctl load /Users/Shared/.launchpad/com.apple.Dock.plist
launchctl start com.apple.Dock.agent

if defaults read /Library/Preferences/FeatureFlags/Domain/SwiftUI.plist Solarium | grep -q "Enabled = 0"; then
    printf "Liquid Glass has been disabled. Control Center and Notification Center don't work correctly with Liquid Glass disabled, therefore relaunching them with Liquid Glass enabled.\n"
    cp /System/Library/LaunchAgents/com.apple.controlcenter.plist /Users/Shared/.launchpad
    plutil -insert EnvironmentVariables -xml "<dict><key>FEATUREFLAGS_ENABLED</key><string>SwiftUI/Solarium</string></dict>" /Users/Shared/.launchpad/com.apple.controlcenter.plist
    launchctl unload /Users/Shared/.launchpad/com.apple.controlcenter.plist
    launchctl load /Users/Shared/.launchpad/com.apple.controlcenter.plist
    launchctl start com.apple.controlcenter

    cp /System/Library/LaunchAgents/com.apple.notificationcenterui.plist /Users/Shared/.launchpad
    plutil -insert EnvironmentVariables -xml "<dict><key>FEATUREFLAGS_ENABLED</key><string>SwiftUI/Solarium</string></dict>" /Users/Shared/.launchpad/com.apple.notificationcenterui.plist
    launchctl unload /Users/Shared/.launchpad/com.apple.notificationcenterui.plist
    launchctl load /Users/Shared/.launchpad/com.apple.notificationcenterui.plist
    launchctl start com.apple.notificationcenterui.agent
else
    printf "Done!\n"
fi