#!/bin/sh

macos_version=$(sw_vers -productVersion | cut -d '.' -f 1)
if [ "$macos_version" -ne 26 ]; then
    echo "This utility requires macOS 26."
    exit 1
fi

if csrutil status | grep -q "disabled"; then
    printf "✅ System Integrity Protection (SIP) is disabled.\n"
else
    printf 'For this to work, you need to turn off System Integrity Protection by running `csrutil disable` in recoveryOS.\n'
    printf 'https://developer.apple.com/documentation/security/disabling-and-enabling-system-integrity-protection\n'
    exit 1
fi

cp /System/Library/LaunchAgents/com.apple.Dock.plist /Users/Shared/.launchpad
plutil -insert EnvironmentVariables -xml "<dict><key>FEATUREFLAGS_DISABLED</key><string>SpotlightUI/SpotlightPlus</string></dict>" /Users/Shared/.launchpad/com.apple.Dock.plist
plutil -replace Program -string /Users/Shared/.launchpad/Dock.app/Contents/MacOS/Dock /Users/Shared/.launchpad/com.apple.Dock.plist

launchctl unload /Users/Shared/.launchpad/com.apple.Dock.plist
launchctl load /Users/Shared/.launchpad/com.apple.Dock.plist
launchctl start com.apple.Dock.agent